name: Healthcare-System-CI

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  # Job no. 1: Code Quality
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install & Validate Backend
        working-directory: ./backend
        run: |
          npm ci
          npx prisma validate
          npm run lint
          npx tsc --noEmit

      - name: Install & Validate Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint
          
  # Job no. 2: Security AUdit
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan Secrets
        uses: gitleaks/gitleaks-actions@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Vulnerability Audit
        run: |
          cd backend && npm audit --audit-level=high
          cd ../frontend && npm audit --audit-level=high

  # Job no. 3: Build & Container scan
  container-build:
    needs: [quality-check, security-audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: | 
          docker build -t healthcare-backend:test \
          -f ./backend/Dockerfile \
          --target runner ./backend
          
      - name: Scan Backend Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'healthcare-backend:test'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Build Frontend Image
        run: |
          docker build -t healthcare-frontend:test \
          -f ./frontend/Dockerfile ./frontend

      - name: Scan Frontend Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: 'healthcare-frontend:test'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
